# the seed order of the teams
ORDERED_TEAMS = [
    "Connecticut",
    "Houston",
    "Purdue",
    "North Carolina",
    "Tennessee",
    "Arizona",
    "Marquette",
    "Iowa State",
    "Baylor",
    "Creighton",
    "Kentucky",
    "Illinois",
    "Duke",
    "Kansas",
    "Auburn",
    "Alabama",
    "BYU",
    "San Diego State",
    "Wisconsin",
    "Saint Mary's",
    "Gonzaga",
    "Clemson",
    "Texas Tech",
    "South Carolina",
    "Florida",
    "Washington State",
    "Texas",
    "Dayton",
    "Nebraska",
    "Utah State",
    "Florida Atlantic",
    "Mississippi State",
    "Michigan State",
    "Texas A&M",
    "TCU",
    "Northwestern",
    "Nevada",
    "Colorado",
    "Drake",
    "New Mexico",
    "Oregon",
    "Colorado State",
    "N.C. State",
    "Duquesne",
    "Grand Canyon",
    "James Madison",
    "McNeese State",
    "UAB",
    "Vermont",
    "Yale",
    "Samford",
    "Charleston",
    "Oakland",
    "Akron",
    "Morehead State",
    "Colgate",
    "Long Beach State",
    "Western Kentucky",
    "South Dakota State",
    "Saint Peter's",
    "Longwood",
    "Stetson",
    "Grambling State",
    "Wagner",
]
# the sportsbook odds for each team winning the entire tournament as of 2024-03-18
ODDS = {
    "Connecticut": 370,
    "Houston": 550,
    "Purdue": 700,
    "Arizona": 1200,
    "North Carolina": 1700,
    "Tennessee": 1700,
    "Iowa State": 2000,
    "Auburn": 2200,
    "Creighton": 2500,
    "Marquette": 2500,
    "Duke": 3000,
    "Kentucky": 3000,
    "Baylor": 3500,
    "Illinois": 3500,
    "Alabama": 4000,
    "Kansas": 4500,
    "Gonzaga": 5000,
    "BYU": 6000,
    "Wisconsin": 6000,
    "Florida": 6500,
    "Michigan State": 6500,
    "Saint Mary's": 6500,
    "San Diego State": 7500,
    "New Mexico": 7500,
    "Texas Tech": 8000,
    "Texas": 10000,
    "Clemson": 12000,
    "TCU": 12000,
    "Nebraska": 12000,
    "Colorado": 15000,
    "Washington State": 15000,
    "Texas A&M": 15000,
    "Mississippi State": 15000,
    "Florida Atlantic": 15000,
    "Dayton": 15000,
    "Oregon": 20000,
    "South Carolina": 20000,
    "Nevada": 20000,
    "Utah State": 20000,
    "Drake": 20000,
    "N.C. State": 25000,
    "Northwestern": 25000,
    "Colorado State": 25000,
    "James Madison": 25000,
    "Grand Canyon": 50000,
    "McNeese State": 50000,
    "Yale": 50000,
    "Samford": 50000,
    "Vermont": 50000,
    "UAB": 100000,
    "Charleston": 100000,
    "Morehead State": 100000,
    "Longwood": 100000,
    "Stetson": 100000,
    "Oakland": 100000,
    "South Dakota State": 100000,
    "Colgate": 100000,
    "Wagner": 100000,
    "Akron": 100000,
    "Saint Peter's": 100000,
    "Western Kentucky": 100000,
    "Long Beach State": 100000,
    "Grambling State": 100000,
    "Duquesne": 100000,
}
# the pairings of teams, ordered so that 1 and 2 play each other, then the winner of that plays the winner of 3 and 4, etc.
TOURNAMENT = [
    "Connecticut",
    "Stetson",
    "Florida Atlantic",
    "Northwestern",
    "San Diego State",
    "UAB",
    "Auburn",
    "Yale",
    "BYU",
    "Duquesne",
    "Illinois",
    "Morehead State",
    "Washington State",
    "Drake",
    "Iowa State",
    "South Dakota State",
    "North Carolina",
    "Wagner",
    "Mississippi State",
    "Michigan State",
    "Saint Mary's",
    "Grand Canyon",
    "Alabama",
    "Charleston",
    "Clemson",
    "New Mexico",
    "Baylor",
    "Colgate",
    "Dayton",
    "Nevada",
    "Arizona",
    "Long Beach State",
    "Houston",
    "Longwood",
    "Nebraska",
    "Texas A&M",
    "Wisconsin",
    "James Madison",
    "Duke",
    "Vermont",
    "Texas Tech",
    "N.C. State",
    "Kentucky",
    "Oakland",
    "Florida",
    "Colorado",
    "Marquette",
    "Western Kentucky",
    "Purdue",
    "Grambling State",
    "Utah State",
    "TCU",
    "Gonzaga",
    "McNeese State",
    "Kansas",
    "Samford",
    "South Carolina",
    "Oregon",
    "Creighton",
    "Akron",
    "Texas",
    "Colorado State",
    "Tennessee",
    "Saint Peter's",
]
